name: Branch build

# Triggers the workflow on push or pull request events
on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print source branch name
        run: |
          echo "GITHUB_REF:$GITHUB_REF"
          export LATESTLOG=$(git log -1 --pretty=%B)
          echo "$(git log -1 --pretty=%B)"
          export SOURCEBRANCH=$(echo $LATESTLOG | awk -F '\\\\n' '{print $1}' |  awk -F '/' '{print $2}' | awk '{print $1}')
          echo "SOURCEBRANCH:$SOURCEBRANCH"
