name: PR Close

on:
  pull_request:
    # types: [closed]
    branches:
      - new_branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Print source branch name
        run: |
          echo "hello"